config/routes.rb
CaInvTool::Application.routes.draw do
  resources :scans

  get "welcome/index"

  resources :scan_items

  resources :inventory_items

  resources :uploads

  resources :scan_batch_file_exports

  resources :file_comparisons

  root :to => 'welcome#index'

end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  attr_accessible :asin, :auction_title, :brand, :buy_it_now_price, :channel_advisor_store_price, :classification, :description, :flag, :inventory_number, :labels, :mpn, :picture_urls, :received_in_inventory, :retail_price, :second_chance_offer_price, :seller_cost, :starting_bid, :total_quantity, :upc, :weight
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all

    @inventory_items = Kaminari.paginate_array(@inventory_items).page(params[:page]).per(250) unless @inventory_items.nil?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @inventory_items }
    end
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
    @inventory_item = InventoryItem.find(params[:id])

    respond_to do |format|
      format.html # create.html.erb
      format.json { render :json => @inventory_item }
    end
  end

  # GET /inventory_items/new
  # GET /inventory_items/new.json
  def new
    @inventory_item = InventoryItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @inventory_item }
    end
  end

  # GET /inventory_items/1/edit
  def edit
    @inventory_item = InventoryItem.find(params[:id])
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(params[:inventory_item])

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to @inventory_item, :notice => 'Inventory item was successfully created.' }
        format.json { render :json => @inventory_item, :status => :created, :location => @inventory_item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @inventory_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /inventory_items/1
  # PUT /inventory_items/1.json
  def update
    @inventory_item = InventoryItem.find(params[:id])

    respond_to do |format|
      if @inventory_item.update_attributes(params[:inventory_item])
        format.html { redirect_to @inventory_item, :notice => 'Inventory item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @inventory_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item = InventoryItem.find(params[:id])
    @inventory_item.destroy

    respond_to do |format|
      format.html { redirect_to inventory_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_for(@inventory_item) do |f| %>
  <% if @inventory_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
      <% @inventory_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auction_title %><br />
    <%= f.text_field :auction_title %>
  </div>
  <div class="field">
    <%= f.label :inventory_number %><br />
    <%= f.text_field :inventory_number %>
  </div>
  <div class="field">
    <%= f.label :total_quantity %><br />
    <%= f.number_field :total_quantity %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :upc %><br />
    <%= f.text_field :upc %>
  </div>
  <div class="field">
    <%= f.label :asin %><br />
    <%= f.text_field :asin %>
  </div>
  <div class="field">
    <%= f.label :mpn %><br />
    <%= f.text_field :mpn %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :starting_bid %><br />
    <%= f.text_field :starting_bid %>
  </div>
  <div class="field">
    <%= f.label :seller_cost %><br />
    <%= f.text_field :seller_cost %>
  </div>
  <div class="field">
    <%= f.label :buy_it_now_price %><br />
    <%= f.text_field :buy_it_now_price %>
  </div>
  <div class="field">
    <%= f.label :retail_price %><br />
    <%= f.text_field :retail_price %>
  </div>
  <div class="field">
    <%= f.label :channel_advisor_store_price %><br />
    <%= f.text_field :channel_advisor_store_price %>
  </div>
  <div class="field">
    <%= f.label :second_chance_offer_price %><br />
    <%= f.text_field :second_chance_offer_price %>
  </div>
  <div class="field">
    <%= f.label :picture_urls %><br />
    <%= f.text_field :picture_urls %>
  </div>
  <div class="field">
    <%= f.label :received_in_inventory %><br />
    <%= f.number_field :received_in_inventory %>
  </div>
  <div class="field">
    <%= f.label :labels %><br />
    <%= f.text_field :labels %>
  </div>
  <div class="field">
    <%= f.label :flag %><br />
    <%= f.text_field :flag %>
  </div>
  <div class="field">
    <%= f.label :classification %><br />
    <%= f.text_field :classification %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_items/edit.html.erb
<h1>Editing inventory_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_item %> |
<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/index.html.erb
<h1>Listing inventory_items</h1>

<p><%= link_to 'Go Home', welcome_index_path %></p>

<%= paginate @inventory_items %>

<table>
  <tr>
    <th>Auction title</th>
    <th>Inventory number</th>
    <th>Total quantity</th>
    <th>Weight</th>
    <th>Upc</th>
    <th>Asin</th>
    <th>Mpn</th>
    <th>Description</th>
    <th>Brand</th>
    <th>Starting bid</th>
    <th>Seller cost</th>
    <th>Buy it now price</th>
    <th>Retail price</th>
    <th>Channel advisor store price</th>
    <th>Second chance offer price</th>
    <th>Picture urls</th>
    <th>Received in inventory</th>
    <th>Labels</th>
    <th>Flag</th>
    <th>Classification</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventory_items.each do |inventory_item| %>
  <tr>
    <td><%= inventory_item.auction_title %></td>
    <td><%= inventory_item.inventory_number %></td>
    <td><%= inventory_item.total_quantity %></td>
    <td><%= inventory_item.weight %></td>
    <td><%= inventory_item.upc %></td>
    <td><%= inventory_item.asin %></td>
    <td><%= inventory_item.mpn %></td>
    <td><%= inventory_item.description %></td>
    <td><%= inventory_item.brand %></td>
    <td><%= inventory_item.starting_bid %></td>
    <td><%= inventory_item.seller_cost %></td>
    <td><%= inventory_item.buy_it_now_price %></td>
    <td><%= inventory_item.retail_price %></td>
    <td><%= inventory_item.channel_advisor_store_price %></td>
    <td><%= inventory_item.second_chance_offer_price %></td>
    <td><%= inventory_item.picture_urls %></td>
    <td><%= inventory_item.received_in_inventory %></td>
    <td><%= inventory_item.labels %></td>
    <td><%= inventory_item.flag %></td>
    <td><%= inventory_item.classification %></td>
    <td><%= link_to 'Show', inventory_item %></td>
    <td><%= link_to 'Edit', edit_inventory_item_path(inventory_item) %></td>
    <td><%= link_to 'Destroy', inventory_item, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @inventory_items %>
<br />

<%= link_to 'New Inventory item', new_inventory_item_path %>

<p><%= link_to 'Go Home', welcome_index_path %></p>

app/views/inventory_items/new.html.erb
<h1>New inventory_item</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Auction title:</b>
  <%= @inventory_item.auction_title %>
</p>

<p>
  <b>Inventory number:</b>
  <%= @inventory_item.inventory_number %>
</p>

<p>
  <b>Total quantity:</b>
  <%= @inventory_item.total_quantity %>
</p>

<p>
  <b>Weight:</b>
  <%= @inventory_item.weight %>
</p>

<p>
  <b>Upc:</b>
  <%= @inventory_item.upc %>
</p>

<p>
  <b>Asin:</b>
  <%= @inventory_item.asin %>
</p>

<p>
  <b>Mpn:</b>
  <%= @inventory_item.mpn %>
</p>

<p>
  <b>Description:</b>
  <%= @inventory_item.description %>
</p>

<p>
  <b>Brand:</b>
  <%= @inventory_item.brand %>
</p>

<p>
  <b>Starting bid:</b>
  <%= @inventory_item.starting_bid %>
</p>

<p>
  <b>Seller cost:</b>
  <%= @inventory_item.seller_cost %>
</p>

<p>
  <b>Buy it now price:</b>
  <%= @inventory_item.buy_it_now_price %>
</p>

<p>
  <b>Retail price:</b>
  <%= @inventory_item.retail_price %>
</p>

<p>
  <b>Channel advisor store price:</b>
  <%= @inventory_item.channel_advisor_store_price %>
</p>

<p>
  <b>Second chance offer price:</b>
  <%= @inventory_item.second_chance_offer_price %>
</p>

<p>
  <b>Picture urls:</b>
  <%= @inventory_item.picture_urls %>
</p>

<p>
  <b>Received in inventory:</b>
  <%= @inventory_item.received_in_inventory %>
</p>

<p>
  <b>Labels:</b>
  <%= @inventory_item.labels %>
</p>

<p>
  <b>Flag:</b>
  <%= @inventory_item.flag %>
</p>

<p>
  <b>Classification:</b>
  <%= @inventory_item.classification %>
</p>


<%= link_to 'Edit', edit_inventory_item_path(@inventory_item) %> |
<%= link_to 'Back', inventory_items_path %>