config/routes.rb
CaInvTool::Application.routes.draw do
  resources :scans

  get "welcome/index"

  resources :scan_items

  resources :inventory_items

  resources :uploads

  resources :scan_batch_file_exports

  resources :file_comparisons

  root :to => 'welcome#index'

end

app/models/scan_item.rb
class ScanItem < ActiveRecord::Base
  attr_accessible :in_inventory, :item_sku, :quantity, :scan_id
  attr_accessor :auction_title, :message

  belongs_to :scan

  def self.get_item_title(sku)
    @auction_title = InventoryItem.find_by_inventory_number(sku).auction_title unless InventoryItem.find_by_inventory_number(sku).nil?
  end

  def self.to_csv(scan_id)
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        if item.scan_id == scan_id
        csv << product.attributes.values_at(*column_names)
        end
      end
    end
  end
end

app/controllers/scan_items_controller.rb
class ScanItemsController < ApplicationController
  # GET /scan_items
  # GET /scan_items.json
  def index
    @scan_items = ScanItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @scan_items }
    end
  end

  # GET /scan_items/1
  # GET /scan_items/1.json
  def show
    @scan_id = params["scan_id"]
    @scan_item = ScanItem.find(params[:id])

    respond_to do |format|
      format.html # create.html.erb
      format.json { render :json => @scan_item }
      format.csv {send_data @scan_item.to_csv(@scan_id)}
    end
  end

  # GET /scan_items/new
  # GET /scan_items/new.json
  def new
    @scan_id = params[:parent_scan_id].to_s.to_i
    @message = params[:message].to_s unless params[:message].nil?
    @item_in_inv = params[:item_in_inv].to_s unless params[:item_in_inv].nil?
    @scan_item = ScanItem.new

    #render 'scan_items/new'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @scan_item }
    end
  end

  # GET /scan_items/1/edit
  def edit
    @scan_item = ScanItem.find(params[:id])
  end

  # POST /scan_items
  # POST /scan_items.json
  def create
    @scan_id = params[:parent_scan_id].to_s.to_i
    already_scanned = false

    scanned_sku = params["scan_item"]["item_sku"]
    scanned_items = ScanItem.find_all_by_scan_id(@scan_id)

    @scan_item = nil

    scanned_items.each do |i|
      @scan_item = i if i.item_sku == scanned_sku
    end

    puts @scan_item.inspect

    if @scan_item.nil?
      @scan_item = ScanItem.new
      @scan_item.item_sku = scanned_sku
      @scan_item.quantity = 1
      @scan_item.scan_id = @scan_id
    else
      already_scanned = true
      @scan_item.quantity += 1
    end

    @scan_item.in_inventory = false
    @scan_item.message = "NOT in Inventory! (#{@scan_item.item_sku})"
    inventory_items = InventoryItem.all

    inventory_items.each do |item|
      if item.inventory_number == @scan_item.item_sku
        @scan_item.in_inventory = true
        puts @scan_item.message = "Item Exists in Inventory: #{ScanItem.get_item_title(@scan_item.item_sku)}"
      end
    end

    @scan_item.save

    respond_to do |format|
        format.html { redirect_to new_scan_item_path(:parent_scan_id => @scan_id, :message => @scan_item.message, :item_in_inv => @scan_item.in_inventory), :notice => 'Scan item was successfully created.' }
        format.json { render :json => @scan_item, :status => :created, :location => @scan_item }
    end
  end

  # PUT /scan_items/1
  # PUT /scan_items/1.json
  def update
    @scan_item = ScanItem.find(params[:id])

    respond_to do |format|
      if @scan_item.update_attributes(params[:scan_item])
        format.html { redirect_to @scan_item.scan, :notice => 'Scan item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @scan_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scan_items/1
  # DELETE /scan_items/1.json
  def destroy
    @scan_id = params[:parent_scan_id].to_s.to_i
    @scan_item = ScanItem.find(params[:id])
    @scan_item.destroy

    respond_to do |format|
      format.html { redirect_to scans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scan_items_helper.rb
module ScanItemsHelper
end

app/views/scan_items/_form.html.erb
<%= form_for(@scan_item) do |f| %>
  <% if @scan_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scan_item.errors.count, "error") %> prohibited this scan_item from being saved:</h2>

      <ul>
      <% @scan_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_sku %><br />
    <%= f.text_field :item_sku %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scan_items/edit.html.erb
<h1>Editing scan_item</h1>

<%= form_for(@scan_item) do |f| %>
    <% if @scan_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scan_item.errors.count, "error") %> prohibited this scan_item from being saved:</h2>

          <ul>
            <% @scan_item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :item_sku %><br />
      <%= f.text_field :item_sku %>
    </div>
    <div class="field">
      <%= f.label :quantity %><br />
      <%= f.number_field :quantity %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Show', @scan_item %> |
<%= link_to 'Back', scans_path %>

app/views/scan_items/index.html.erb
<h1>Listing Scanned Items</h1>

<table>
  <tr>
    <th>Item Sku</th>
    <th>Quantity</th>
    <th>In Inventory?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scan_items.each do |scan_item| %>
  <tr>
    <td><%= scan_item.item_sku %></td>
    <td><%= scan_item.quantity %></td>
    <td><%= scan_item.in_inventory %></td>
    <td><%= link_to 'Show', scan_item %></td>
    <td><%= link_to 'Edit', edit_scan_item_path(scan_item) %></td>
    <td><%= link_to 'Destroy', scan_item, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scan Item', new_scan_item_path %> | <%= link_to 'Go Home', welcome_index_path %>

app/views/scan_items/new.html.erb
<h1>Scan in New Item</h1>



<%= form_for(@scan_item) do |f| %>
    <% if @scan_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scan_item.errors.count, "error") %> prohibited this scan_item from being saved:</h2>

          <ul>
            <% @scan_item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h1 class='<%= @item_in_inv %>'><%= @message %></h1>

    <p>Current Scan Id: <%= @scan_id.inspect %></p>

    <div class="field">
      <%= hidden_field_tag 'parent_scan_id', @scan_id.to_i %>
    </div>

    <div class="field">
      <%= f.label :item_sku %><br />
      <%= f.text_field :item_sku %>
    </div>
    <script type="text/javascript" language="JavaScript">
        document.forms['new_scan_item'].elements['scan_item[item_sku]'].focus();
    </script>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back to Scanned Items', scan_path(@scan_id) %>

app/views/scan_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scan Id:</b>
  <%= @scan_item.scan_id %>
</p>

<p>
  <b>Item sku:</b>
  <%= @scan_item.item_sku %>
</p>

<p>
  <b>Quantity:</b>
  <%= @scan_item.quantity %>
</p>

<p>
  <b>In inventory:</b>
  <%= @scan_item.in_inventory %>
</p>


<%= link_to 'Edit', edit_scan_item_path(@scan_item) %> |
<%= link_to 'Back', scan_path(@scan_id) %>