config/routes.rb
CaInvTool::Application.routes.draw do
  resources :scans

  get "welcome/index"

  resources :scan_items

  resources :inventory_items

  resources :uploads

  resources :scan_batch_file_exports

  resources :file_comparisons

  root :to => 'welcome#index'

end

app/models/scan.rb
class Scan < ActiveRecord::Base
  attr_accessible :finished, :imported, :title
  attr_readonly :id
  attr_accessor :last_in_inventory, :last_inventory_number, :last_message

  has_many :scan_items, :dependent => :destroy

  def add_scan_message_info(in_inventory, inventory_number)
    @last_in_inventory = in_inventory
    @last_inventory_number = inventory_number
    @last_inventory_title = InventoryItem.find_by_inventory_number(inventory_number).auction_title

    if @last_in_inventory
      @last_message = "Last Item is already in Inventory! (#{@last_inventory_title})"
    else
      @last_message = "Not in Inventory!"
    end
  end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  # GET /scans
  # GET /scans.json
  def index
    @scans = Scan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @scans }
    end
  end

  # GET /scans/1
  # GET /scans/1.json
  def show
    @scan = Scan.find(params[:id])

    @scan_items = ScanItem.find_all_by_scan_id(@scan.id)

    respond_to do |format|
      format.html # create.html.erb
      format.json { render :json => @scan }
    end
  end

  # GET /scans/new
  # GET /scans/new.json
  def new
    @scan = Scan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @scan }
    end
  end

  # GET /scans/1/edit
  def edit
    @scan = Scan.find(params[:id])
  end

  # POST /scans
  # POST /scans.json
  def create
    @scan = Scan.new(params[:scan])

    respond_to do |format|
      if @scan.save
        format.html { redirect_to @scan, :notice => 'Scan was successfully created.' }
        format.json { render :json => @scan, :status => :created, :location => @scan }
      else
        format.html { render :action => "new" }
        format.json { render :json => @scan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scans/1
  # PUT /scans/1.json
  def update
    @scan = Scan.find(params[:id])

    respond_to do |format|
      if @scan.update_attributes(params[:scan])
        format.html { redirect_to @scan, :notice => 'Scan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @scan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1
  # DELETE /scans/1.json
  def destroy
    @scan = Scan.find(params[:id])
    @scan.destroy

    respond_to do |format|
      format.html { redirect_to scans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/scans/_form.html.erb
<%= form_for(@scan) do |f| %>
  <% if @scan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scan.errors.count, "error") %> prohibited this scan from being saved:</h2>

      <ul>
      <% @scan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :finished %><br />
    <%= f.check_box :finished %>
  </div>
  <div class="field">
    <%= f.label :imported %><br />
    <%= f.check_box :imported %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scans/edit.html.erb
<h1>Editing scan</h1>

<%= render 'form' %>

<%= link_to 'Show', @scan %> |
<%= link_to 'Back', scans_path %>

app/views/scans/index.html.erb
<h1>Listing Scan Batches</h1>

<table>
  <tr>
    <th>Batch ID</th>
    <th>Title</th>
    <th>Finished?</th>
    <th>Imported?</th>
    <th>Date Added</th>
    <th>Last Updated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scans.each do |scan| %>
  <tr>
    <td><%= scan.id%></td>
    <td><%= scan.title %></td>
    <td><%= scan.finished %></td>
    <td><%= scan.imported %></td>
    <td><%= scan.created_at %></td>
    <td><%= scan.updated_at %></td>
    <td><%= link_to 'Scan Items/View Batch', scan %></td>
    <td><%= link_to 'Edit', edit_scan_path(scan) %></td>
    <td><%= link_to 'Destroy', scan, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scan Batch', new_scan_path %> | <%= link_to 'Go Home', welcome_index_path %>

app/views/scans/new.html.erb
<h1>New scan batch</h1>

<%= render 'form' %>

<%= link_to 'Back', scans_path %>

app/views/scans/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<p>
  <b>Batch ID:</b> <%= @scan.id %><br/>
  <b>Title:</b> <%= @scan.title %><br/>
  <b>Finished:</b> <%= @scan.finished %><br/>
  <b>Imported:</b> <%= @scan.imported %><br/>
  <b>Date Added:</b> <%= @scan.created_at %><br/>
  <b>Last Updated:</b> <%= @scan.updated_at %><br/>
</p>

<table>
  <tr>
    <th>Item Sku</th>
    <th>Item Title</th>
    <th>Quantity Recently Scanned</th>
    <th>In Inventory?</th>
    <th></th>
    <th></th>
  </tr>

  <h1 class='<%= @scan.last_in_inventory %>'><%= @scan.last_message %></h1>


  <% @scan_items.each do |scan_item| %>
      <tr>
        <td><%= scan_item.item_sku %></td>
        <td><%= ScanItem.get_item_title(scan_item.item_sku) %></td>
        <td><%= scan_item.quantity %></td>
        <td class='<%= scan_item.in_inventory %>'><%= scan_item.in_inventory %></td>
        <td><%= link_to 'Edit', edit_scan_item_path(scan_item) %></td>
        <td><%= link_to 'Destroy', scan_item, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />
<%= link_to 'Add/Scan In New Inventory', new_scan_item_path(:parent_scan_id => @scan.id) %> |
<%= link_to 'Edit Scan Batch Details', edit_scan_path(@scan) %> |
<%= link_to 'Go Back to Scan Batches', scans_path %> |
<%= link_to 'Go to Export File Page', scan_batch_file_exports_path %> |
<%= link_to 'Go Home', scans_path %>